//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Integrateur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public decimal IDAdmission { get; set; }
        public Nullable<bool> ChirurgiePrograme { get; set; }
        public Nullable<System.DateTime> DateAdmission { get; set; }
        public Nullable<System.DateTime> DateChirurgie { get; set; }
        public Nullable<System.DateTime> DateConge { get; set; }
        public Nullable<bool> Televiseur { get; set; }
        public Nullable<bool> Telephone { get; set; }
        public decimal Nss { get; set; }
        public decimal NumeroLit { get; set; }
        public decimal IDMedecin { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
